import { readFileSync, writeFileSync } from 'fs'
import getAchieved from '../achieved'
import template1 from './readme-1'

const templates = [
    template1
]

const readme = () => {
    const config = JSON.parse(readFileSync("public/settings.json").toString())
    const achieved = getAchieved()
    //  const template = templates[config.template - 1]
    const template = templates[0] // Pending config

    let content = template(config, achieved)
    let sign = "\n***\n_This README was generated by [aoc-node-starter](https://github.com/mariofdezzz/aoc-node-starter)_"

    writeFileSync("README.md", content + sign)
}

export default readme;